export const CART_ACTION_TYPES = {
  SET_CART_ITEMS: 'cart/SET_CART_ITEMS',
  SET_CART_IS_OPEN: 'cart/SET_CART_IS_OPEN',
  SET_TOTAL_CART_ITEMS: 'cart/SET_TOTAL_CART_ITEMS',
  SET_TOTAL_AMOUNT: 'cart/SET_TOTAL_AMOUNT',
};
